#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

runApplication -o blockMesh
runApplication -o decomposePar -force

runParallel -o snappyHexMesh
runParallel -o renumberMesh

#------------------------------------------------------------------------------
