#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

rm -r processor*/0
ls -d processor* | xargs -I {} cp -r 0.orig {}/0

runParallel -o $(getApplication)

printf "Done\n"

#------------------------------------------------------------------------------
